# Generated by Django 3.2.18 on 2024-03-06 11:35

from django.db import migrations, models
import passerelle_imio_apims_certificats_population.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0030_resourcelog_base_resour_appname_298cbc_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApimsCertificatsPopulationConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifier')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(blank=True, default='https://api-staging.imio.be/bosa/v1', help_text='URL de APIMS Certificats Population', max_length=128, validators=[passerelle_imio_apims_certificats_population.models.validate_url], verbose_name='URL')),
                ('username', models.CharField(blank=True, help_text='Utilisateur APIMS Certificats Population', max_length=128, verbose_name='Utilisateur')),
                ('password', models.CharField(blank=True, help_text='Mot de passe APIMS Certificats Population', max_length=128, verbose_name='Mot de passe')),
                ('municipality_nis_code', models.CharField(blank=True, help_text="Code NIS d'identification de l'organisme dans APIMS Certificats Population", max_length=128, verbose_name="Code NIS de l'organisme")),
                ('users', models.ManyToManyField(blank=True, related_name='_passerelle_imio_apims_certificats_population_apimscertificatspopulationconnector_users_+', related_query_name='+', to='base.ApiUser')),
            ],
            options={
                'verbose_name': 'Connecteur APIMS Certificats Population',
            },
        ),
    ]
