# Generated by Django 3.2.18 on 2024-03-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passerelle_imio_apims_certificats_population', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimscertificatspopulationconnector',
            name='municipality_nis_code',
        ),
        migrations.AddField(
            model_name='apimscertificatspopulationconnector',
            name='municipality_token',
            field=models.CharField(blank=True, help_text="Slug d'identification de l'organisme dans APIMS Certificats Population", max_length=128, verbose_name="slug de l'instance"),
        ),
    ]
